# Master docker-compose file that starts all the containers
name: homelab

include:
  - ./budgetron/docker-compose.yml
  - ./glance/docker-compose.yml
  - ./jellyfin/docker-compose.yml
  - ./portainer/docker-compose.yml
  - ./traefik/docker-compose.yml
  - ./watchtower/docker-compose.yml
