# Master docker-compose file that starts all the containers
name: homelab

include:
  - ./authentik/docker-compose.yml
  - ./budgetron/docker-compose.yml
  - ./drizzle-gateway/docker-compose.yml
  - ./glance/docker-compose.yml
  - ./home-assistant/docker-compose.yml
  - ./jellyfin/docker-compose.yml
  - ./matter-server/docker-compose.yml
  - ./open-webui/docker-compose.yml
  - ./pgbackweb/docker-compose.yml
  - ./portainer/docker-compose.yml
  - ./traefik/docker-compose.yml
  - ./watchtower/docker-compose.yml
