# Master docker-compose file that starts all the containers
include:
  - ./traefik/docker-compose.yml
  - ./glance/docker-compose.yml
  - ./budgetron/docker-compose.yml
  - ./watchtower/docker-compose.yml
