services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80 # HTTP port
      - 443:443 # HTTPS port
      - 8080:8080 # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./configs/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./configs/conf/:/etc/traefik/conf/
      - ./configs/certs/:/etc/traefik/certs/
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    labels:
      # Proxy setup to Traefik Dashboard & Certificate setup
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
      - traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN}
      - traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAIN}
      - traefik.http.routers.traefik.service=api@internal

      # Proxy setup to Ollama Service (External)
      - traefik.http.routers.ollama.rule=Host(`ollama.${DOMAIN}`)
      - traefik.http.routers.ollama.entrypoints=https
      - traefik.http.routers.ollama.tls=true
      - traefik.http.services.ollama.loadbalancer.server.url=${OLLAMA_URL}

      # Glance widget setup
      - glance.hide=false
      - glance.name=Traefik
      - glance.icon=/assets/traefik.svg
      - glance.description=Traefik is a modern reverse proxy and load balancer.
      - glance.category=Proxy

      # Auto update
      - com.centurylinklabs.watchtower.enable=true
