services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=43200  # 12 hours = 12 * 60 * 60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CONFIG_PATH}:/config.json:ro
    labels:
      # Glance widget setup
      - glance.hide=false
      - glance.name=Watchtower
      - glance.icon=/assets/watchtower.svg
      - glance.description=Watchtower is a tool that automatically updates Docker containers.
      - glance.category=System
