services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    labels:
      # Proxy setup
      - traefik.enable=true
      - traefik.http.routers.glance.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.glance.entrypoints=https
      - traefik.http.routers.glance.tls=true
      - traefik.http.services.glance.loadbalancer.server.port=8080

      # Auto update
      - com.centurylinklabs.watchtower.enable=true
